# Generated by Django 6.0 on 2026-01-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('opening_time', models.TimeField()),
                ('closeing_time', models.TimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image', models.ImageField(upload_to='restaurants/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
