# Generated by Django 6.0 on 2026-01-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='closeing_time',
            new_name='closing_time',
        ),
    ]
