# Generated by Django 6.0 on 2026-01-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_closeing_time_restaurant_closing_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='dishes/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dish_type', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], max_length=10)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='App.restaurant')),
            ],
        ),
    ]
